#!/usr/bin/env bash
# claude-packs installer — installs the `claude-packs` CLI onto this device.
#
# Install (from a clone):
#   ./install.sh
#
# Install (no clone needed):
#   curl -fsSL https://raw.githubusercontent.com/St-Luciferr/claude-skills-pack/main/install.sh | bash
#
# Install this checkout instead of cloning from GitHub (for contributors):
#   ./install.sh --local
#
# Remove the CLI:
#   ./install.sh --uninstall        (or: claude-packs self-uninstall)
#
# What it does:
#   1. puts a managed copy of the registry (CLI + bundles) in ~/.claude-packs
#   2. writes a `claude-packs` launcher into ~/.local/bin (must be on your PATH)
#
# Requirements: bash + coreutils/awk. No Node, no npm. git is needed to install from
# a remote URL and for `claude-packs self-update`.
# Afterwards, manage bundles with the installed command:
#   claude-packs list | install <bundle> | update | uninstall <bundle>
#
# Environment overrides:
#   CLAUDE_PACKS_HOME   registry location   (default: ~/.claude-packs)
#   CLAUDE_PACKS_BIN    launcher directory  (default: ~/.local/bin)
#   CLAUDE_PACKS_REPO   git URL to install from
set -euo pipefail

REPO_URL="${CLAUDE_PACKS_REPO:-https://github.com/St-Luciferr/claude-skills-pack.git}"
HOME_DIR="${CLAUDE_PACKS_HOME:-$HOME/.claude-packs}"
BIN_DIR="${CLAUDE_PACKS_BIN:-$HOME/.local/bin}"
LAUNCHER="${BIN_DIR}/claude-packs"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd || echo '')"

say()  { printf '%s\n' "$*"; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- args ----------------------------------------------------------------------
USE_LOCAL=0
if [[ "${1:-}" == "--local" ]]; then USE_LOCAL=1; shift; fi

# --- uninstall ----------------------------------------------------------------
if [[ "${1:-}" == "--uninstall" || "${1:-}" == "uninstall" ]]; then
  removed=0
  [[ -e "$LAUNCHER" ]] && { rm -f "$LAUNCHER"; say "removed ${LAUNCHER}"; removed=1; }
  [[ -d "$HOME_DIR" ]] && { rm -rf "$HOME_DIR"; say "removed ${HOME_DIR}"; removed=1; }
  [[ $removed -eq 0 ]] && say "Nothing to remove (no install found)."
  say
  say "claude-packs CLI removed. Bundles already installed into your projects"
  say "or ~/.claude are untouched — remove those with 'claude-packs uninstall' first."
  exit 0
fi

# --- prerequisites ------------------------------------------------------------
# The CLI is pure bash — no Node, no npm. Only coreutils + awk are needed to run it;
# git is needed to install from a remote and to self-update.

# --- fetch the registry into HOME_DIR ------------------------------------------
have_local()  { [[ -n "$SCRIPT_DIR" && -f "${SCRIPT_DIR}/bin/claude-packs" && -d "${SCRIPT_DIR}/bundles" ]]; }
have_git()    { command -v git >/dev/null 2>&1; }

install_local() { # copy the checkout we're running from; no .git, so no self-update
  say "Copying local checkout -> ${HOME_DIR} ..."
  rm -rf "$HOME_DIR"
  mkdir -p "$HOME_DIR"
  cp -R "${SCRIPT_DIR}/bin" "${SCRIPT_DIR}/bundles" "$HOME_DIR/"
  cp "${SCRIPT_DIR}/VERSION" "$HOME_DIR/" 2>/dev/null || true
  cp "${SCRIPT_DIR}/README.md" "$HOME_DIR/" 2>/dev/null || true
  say "note: installed from a local copy — 'claude-packs self-update' is unavailable"
  say "      (re-run install.sh without --local to switch to a git-backed install)."
}

if [[ $USE_LOCAL -eq 1 ]]; then
  have_local || die "--local needs to run from a checkout containing bin/claude-packs and bundles/"
  install_local
elif [[ -d "${HOME_DIR}/.git" ]] && have_git; then
  say "Updating existing registry in ${HOME_DIR} ..."
  git -C "$HOME_DIR" pull --ff-only || say "warning: git pull failed — keeping existing content"
elif have_git; then
  say "Cloning ${REPO_URL} -> ${HOME_DIR} ..."
  rm -rf "$HOME_DIR"
  git clone --depth 1 "$REPO_URL" "$HOME_DIR" >/dev/null 2>&1 \
    || die "git clone failed from ${REPO_URL}
If you meant to install this checkout instead, re-run: ./install.sh --local"
elif have_local; then
  say "warning: git not found — falling back to this checkout."
  install_local
else
  die "can't find the registry. Install git, run this from a clone, or set CLAUDE_PACKS_REPO."
fi

[[ -f "${HOME_DIR}/bin/claude-packs" ]] || die "install looks incomplete: ${HOME_DIR}/bin/claude-packs missing"
chmod +x "${HOME_DIR}/bin/claude-packs" 2>/dev/null || true

# --- write the launcher --------------------------------------------------------
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# claude-packs launcher (generated by install.sh — do not edit)
export CLAUDE_PACKS_HOME="${HOME_DIR}"
export CLAUDE_PACKS_LAUNCHER="${LAUNCHER}"
exec "${HOME_DIR}/bin/claude-packs" "\$@"
EOF
chmod +x "$LAUNCHER"

say
say "✓ Installed claude-packs $(cat "${HOME_DIR}/VERSION" 2>/dev/null || echo '')"
say "  registry: ${HOME_DIR}"
say "  command:  ${LAUNCHER}"

# --- PATH guidance -------------------------------------------------------------
case ":${PATH}:" in
  *":${BIN_DIR}:"*) ON_PATH=1 ;;
  *) ON_PATH=0 ;;
esac

if [[ $ON_PATH -eq 0 ]]; then
  case "${SHELL:-}" in
    */zsh) PROFILE="~/.zshrc" ;;
    */bash) PROFILE="~/.bashrc" ;;
    *) PROFILE="your shell profile" ;;
  esac
  say
  say "⚠ ${BIN_DIR} is not on your PATH. Add it to ${PROFILE}:"
  say "    export PATH=\"${BIN_DIR}:\$PATH\""
  say "  then restart your shell (or run: export PATH=\"${BIN_DIR}:\$PATH\")"
fi

say
say "Next steps:"
say "  claude-packs list                          # see available bundles"
say "  claude-packs install aws-connect           # into ~/.claude (all projects)"
say "  claude-packs install aws-connect -p .      # into ./.claude (this project)"
say "  claude-packs self-update                   # pull newer bundles later"
